# Generated by Django 5.2.17 on 2026-09-25 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('party_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number.', regex='^[6-9]\\d{9}$')])),
                ('alternate_contact', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number.', regex='^[6-9]\\d{9}$')])),
                ('function_type', models.CharField(choices=[('wedding', 'Wedding'), ('reception', 'Reception'), ('engagement', 'Engagement'), ('birthday', 'Birthday'), ('conference', 'Conference'), ('seminar', 'Seminar'), ('anniversary', 'Anniversary'), ('naming_ceremony', 'Naming Ceremony'), ('puberty_ceremony', 'Puberty Ceremony'), ('other', 'Other')], max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_days', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('from_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('received_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('not_paid', 'Not Paid'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid')], default='not_paid', max_length=20)),
                ('booking_status', models.CharField(choices=[('upcoming', 'Upcoming'), ('today', 'Today'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-start_date', 'from_time'],
                'indexes': [models.Index(fields=['booking_number'], name='bookings_booking_502bea_idx'), models.Index(fields=['start_date', 'end_date'], name='bookings_start_d_527bc3_idx'), models.Index(fields=['booking_status'], name='bookings_booking_ab1f8c_idx'), models.Index(fields=['payment_status'], name='bookings_payment_3ea9ef_idx'), models.Index(fields=['party_name'], name='bookings_party_n_fabd50_idx'), models.Index(fields=['contact_number'], name='bookings_contact_354151_idx'), models.Index(fields=['function_type'], name='bookings_functio_7b0afe_idx'), models.Index(fields=['start_date'], name='bookings_start_d_94c02c_idx'), models.Index(fields=['end_date'], name='bookings_end_dat_49719f_idx')],
            },
        ),
    ]
