# Generated by Django 5.2.17 on 2026-09-25 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('category', models.CharField(choices=[('cleaning', 'Cleaning'), ('electricity', 'Electricity'), ('decoration', 'Decoration'), ('maintenance', 'Maintenance'), ('repair', 'Repair'), ('staff', 'Staff'), ('transportation', 'Transportation'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['expense_date'], name='expenses_expense_43600a_idx'), models.Index(fields=['category'], name='expenses_categor_a6f264_idx'), models.Index(fields=['created_at'], name='expenses_created_753bda_idx')],
            },
        ),
    ]
